namespace AdrPortal.Core.Workflows;

/// <summary>
/// Represents the persisted Git/PR state after processing a queue item.
/// </summary>
public sealed record GitPrWorkflowProcessingResult
{
    /// <summary>
    /// Gets the queue item identifier.
    /// </summary>
    public required Guid QueueItemId { get; init; }

    /// <summary>
    /// Gets the branch name used for the Git operation.
    /// </summary>
    public required string BranchName { get; init; }

    /// <summary>
    /// Gets the commit SHA generated by branch updates, if available.
    /// </summary>
    public string? CommitSha { get; init; }

    /// <summary>
    /// Gets the pull request URL associated with the queue item when available.
    /// </summary>
    public Uri? PullRequestUrl { get; init; }

    /// <summary>
    /// Gets the pull request number associated with the queue item when available.
    /// </summary>
    public int? PullRequestNumber { get; init; }
}
