// <auto-generated />
using System;
using AdrPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdrPortal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AdrPortalDbContext))]
    [Migration("20260319191038_AddGlobalAdrLibraryPhase8UiSync")]
    partial class AddGlobalAdrLibraryPhase8UiSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdr", b =>
                {
                    b.Property<Guid>("GlobalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("GlobalId");

                    b.ToTable("GlobalAdrs", (string)null);
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseTemplateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLocalChanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LastKnownStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalAdrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoRelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("GlobalId", "RepositoryId", "LocalAdrNumber")
                        .IsUnique();

                    b.ToTable("GlobalAdrInstances", (string)null);
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrUpdateProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("LocalAdrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProposedFromVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedMarkdownContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedTitle")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("GlobalId", "RepositoryId", "LocalAdrNumber", "IsPending");

                    b.ToTable("GlobalAdrUpdateProposals", (string)null);
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GlobalId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("GlobalAdrVersions", (string)null);
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.ManagedRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdrFolder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("docs/adr");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitRemoteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("InboxFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagedRepositories", (string)null);
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrInstance", b =>
                {
                    b.HasOne("AdrPortal.Core.Entities.GlobalAdr", "GlobalAdr")
                        .WithMany("Instances")
                        .HasForeignKey("GlobalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdrPortal.Core.Entities.ManagedRepository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalAdr");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrUpdateProposal", b =>
                {
                    b.HasOne("AdrPortal.Core.Entities.GlobalAdr", "GlobalAdr")
                        .WithMany("UpdateProposals")
                        .HasForeignKey("GlobalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdrPortal.Core.Entities.ManagedRepository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalAdr");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdrVersion", b =>
                {
                    b.HasOne("AdrPortal.Core.Entities.GlobalAdr", "GlobalAdr")
                        .WithMany("Versions")
                        .HasForeignKey("GlobalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalAdr");
                });

            modelBuilder.Entity("AdrPortal.Core.Entities.GlobalAdr", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("UpdateProposals");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
